CREATE DATABASE QLDVCC
USE QLDVCC

create table NHANVIEN(
	MA_NV VARCHAR(10) PRIMARY KEY,
	TEN_NV NVARCHAR(100) not null,
	NGAYSINH DATE,
	QUEQUAN NVARCHAR(100),
	SODT VARCHAR(10) not null,
	CCCD VARCHAR(12) unique,
	DIACHI NVARCHAR(100) not null,
	PHONGBAN NVARCHAR(100) not null,
	CHUCVU NVARCHAR (100),
	LUONG FLOAT not null,
	THOIGIAN_BATDAU_CONGTAC DATE not null,
);

create TABLE HOGIADINH (

	MAHO VARCHAR(30),
	TENCHUHO NVARCHAR(100),
	SDTLIENLAC VARCHAR(12) UNIQUE,
	SOTHANHVIEN INT,
	SOPHUONGTIEN INT,
	NGAYCHUYENDEN DATE,
	SOPHONG NVARCHAR(10) UNIQUE, 
	PRIMARY KEY (MAHO)
)

CREATE TABLE PhanCongNhiemVu(
	MaPhanCong NVARCHAR(10) PRIMARY KEY,
	MA_NV VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MA_NV) ON DELETE CASCADE,
	MAHO VARCHAR(30) FOREIGN KEY REFERENCES HOGIADINH(MAHO) ON DELETE CASCADE,
	NhiemVu NVARCHAR(30),
	NgayPhanCong DATE,
	MaHoanThanh BIT DEFAULT 0,
	TrangThaiHoanThanh CHAR(30) DEFAULT 'Chưa hoàn thành công việc',
	GhiChu NVARCHAR(100)
)

CREATE table DANCU
(
MAHO varchar(30) references HOGIADINH(MAHO) on delete cascade,
MADANCU char(10) primary key not null,
HOVATEN nvarchar(40) not null,
GIOITINH nvarchar(20) not null,
NAMSINH DATE  not null,
NGHENGHIEP nvarchar(40),
CCCD char(12) unique,
QUEQUAN nvarchar(30) not null,
SDT char(10) unique check (SDT like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)

CREATE TABLE QUANLIDICHVU(
    TENDICHVU NVARCHAR(100) ,
	MAQUANLY NVARCHAR(10) NOT NULL PRIMARY KEY,
	MAHO VARCHAR(30) FOREIGN KEY REFERENCES HOGIADINH(MAHO) ON DELETE CASCADE,
	NGAY_THU DATE not null,
	TIENDICHVU FLOAT ,
	DONVI CHAR(10) NOT NULL,
);
CREATE TABLE TONGTIENDICHVU(
	MAHO VARCHAR(30) FOREIGN KEY REFERENCES HOGIADINH(MAHO) ON DELETE CASCADE,
	TONGTIEN FLOAT,
	MATRANGTHAI BIT DEFAULT 0,
	TRANGTHAI NVARCHAR(30) DEFAULT 'Chưa thanh toán',
	GHICHU NVARCHAR(50)
)
CREATE TABLE Phanhoi(
		Maphanhoi NVARCHAR(10) NOT NULL PRIMARY KEY,
		MAHO VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES HOGIADINH(MAHO) ON DELETE CASCADE,
		Noidung NVARCHAR(500),
		NgayPhanHoi DATE DEFAULT GETDATE()
);

CREATE TABLE TinhtrangPhanhoi(
	MaTinhTrang NVARCHAR(10) PRIMARY KEY,
	Maphanhoi NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES Phanhoi(Maphanhoi) ON DELETE CASCADE,
	Tinhtrang NVARCHAR(15) DEFAULT 'Chưa giải quyết' NOT NULL,
	Matrangthai BIT DEFAULT 0 NOT NULL,
);























